# Recitation 0.3 — NumPy Fundamentals

This notebook walks through the material covered in Recitation 0.3.  
We will look at:

- What NumPy is and how to import it
- Basic array types (scalar, vector, matrix, tensor)
- Array attributes: `ndim`, `shape`, `size`, `dtype`
- Indexing, slicing, and boolean masking
- Axis-based operations (summing over rows/columns)
- Reshaping, transposing, expanding and squeezing dimensions
- Combining arrays (concatenation vs stacking)
- Broadcasting
- Elementwise vs matrix multiplication


## Imports and version

In [44]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## Basic array types

NumPy's core object is the **`ndarray`** — an N‑dimensional array of numbers.

We will look at four simple cases and inspect their attributes:
- scalar (0‑D)
- vector (1‑D)
- matrix (2‑D)
- tensor (3‑D and above)


In [45]:
# Scalar (0‑D)
x = np.array(6)
print("x:", x)
print("ndim:", x.ndim)
print("shape:", x.shape)
print("size:", x.size)
print("dtype:", x.dtype)

x: 6
ndim: 0
shape: ()
size: 1
dtype: int64


In [46]:
# Vector (1‑D)
v = np.array([1, 2, 3])
print("v:", v)
print("ndim:", v.ndim)
print("shape:", v.shape)
print("size:", v.size)
print("dtype:", v.dtype)

v: [1 2 3]
ndim: 1
shape: (3,)
size: 3
dtype: int64


In [47]:
# Matrix (2‑D)
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print("M:\n", M)
print("ndim:", M.ndim)
print("shape:", M.shape)

M:
 [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)


In [48]:
# 3‑D tensor
T = np.arange(2*3*4).reshape(2, 3, 4)
print("T shape:", T.shape)
print("ndim:", T.ndim)

T shape: (2, 3, 4)
ndim: 3


## Data types (`dtype`) and precision

Python is dynamically typed, but NumPy arrays have a **fixed data type**.
If we are not careful, we can lose precision when working with floats.


In [49]:
ints = np.array([1, 2, 3])
floats_default = np.array([1.2, 2.5, 3.8])
floats32 = np.array([1.2, 2.5, 3.8], dtype=np.float32)

print("ints dtype:", ints.dtype)
print("floats_default dtype:", floats_default.dtype)
print("floats32 dtype:", floats32.dtype)

ints dtype: int64
floats_default dtype: float64
floats32 dtype: float32


If you know you need floating‑point values (for example, when normalizing
image data), it is safer to create the array with a floating dtype explicitly,
e.g. `dtype=np.float32`.

## Convenience initialisers

NumPy provides helper functions to quickly build common arrays.


In [50]:
print("zeros:")
print(np.zeros((2, 3)))

print("\nones:")
print(np.ones((2, 3)))

print("\nidentity matrix:")
print(np.eye(3))

zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

ones:
[[1. 1. 1.]
 [1. 1. 1.]]

identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
print("arange 0..9:", np.arange(10))
print("linspace 0..1 (5 points):", np.linspace(0, 1, 5))

arange 0..9: [0 1 2 3 4 5 6 7 8 9]
linspace 0..1 (5 points): [0.   0.25 0.5  0.75 1.  ]


In [52]:
rng = np.random.default_rng(seed=42)
print("random normal (2x3):\n", rng.normal(size=(2, 3)))

random normal (2x3):
 [[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]]


## Indexing conventions: row/column (`i, j`) vs `x, y`

NumPy uses **row, column** (`i, j`) indexing:  
`arr[i, j]` means *row `i`, column `j`*.

This is different from the `(x, y)` convention often used for plots or images,
where `x` is the horizontal axis and `y` is the vertical axis.


In [53]:
A = np.arange(1, 13).reshape(3, 4)
print("A =\n", A)

# Row 2 (third row), column 1 (second column)
print("A[2, 1] =", A[2, 1])

A =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A[2, 1] = 10


## Axis operations

Many NumPy functions take an `axis` argument.

- `axis=0` → operate **down the rows** (collapse the row dimension)
- `axis=1` → operate **across columns** for each row


In [54]:
B = np.array([[1, 2, 3],
               [4, 5, 6]])

print("B =\n", B)
print("sum over axis=0 (column‑wise):", np.sum(B, axis=0))
print("sum over axis=1 (row‑wise):", np.sum(B, axis=1))

B =
 [[1 2 3]
 [4 5 6]]
sum over axis=0 (column‑wise): [5 7 9]
sum over axis=1 (row‑wise): [ 6 15]


In [55]:
print("min over axis=0:", np.min(B, axis=0))
print("argmax over axis=1:", np.argmax(B, axis=1))

min over axis=0: [1 2 3]
argmax over axis=1: [2 2]


## Slicing

Slicing lets us take sub‑arrays using the `start:stop:step` syntax.


In [56]:
arr = np.arange(10)
print("arr:", arr)
print("even indices arr[::2]:", arr[::2])
print("reversed arr[::-1]:", arr[::-1])

arr: [0 1 2 3 4 5 6 7 8 9]
even indices arr[::2]: [0 2 4 6 8]
reversed arr[::-1]: [9 8 7 6 5 4 3 2 1 0]


In [57]:
C = np.arange(1, 13).reshape(3, 4)
print("C =\n", C)

print("rows 0..1, cols 1..3: \n", C[0:2, 1:3])

# all rows, column 2
print("column 2: ", C[:, 2])

C =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows 0..1, cols 1..3: 
 [[2 3]
 [6 7]]
column 2:  [ 3  7 11]


## Boolean masking

A **mask** is a boolean array we can use to filter another array.


In [58]:
nums = np.arange(1, 11)
mask = (nums % 2 == 0)
print("nums:", nums)
print("mask:", mask)
print("even numbers:", nums[mask])

nums: [ 1  2  3  4  5  6  7  8  9 10]
mask: [False  True False  True False  True False  True False  True]
even numbers: [ 2  4  6  8 10]


## Reshaping, transposing, expanding and squeezing

Reshaping allows us to change the view of the data without copying it.


In [59]:
data = np.arange(20)
print("data:", data)

M = data.reshape(4, 5)
print("\nreshaped to 4x5:\n", M)

T = M.T
print("\ntranspose (5x4):\n", T)

data: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

reshaped to 4x5:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

transpose (5x4):
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [60]:
v = np.array([1, 2, 3])
print("v shape:", v.shape)

# Add a new axis at the front (1, 3)
v_row = v[np.newaxis, :]
print("v_row shape:", v_row.shape)

# Add a new axis at the end (3, 1)
v_col = v[:, np.newaxis]
print("v_col shape:", v_col.shape)

# Squeeze removes axes of length 1
print("squeezed v_row shape:", np.squeeze(v_row).shape)

v shape: (3,)
v_row shape: (1, 3)
v_col shape: (3, 1)
squeezed v_row shape: (3,)


## Concatenation vs stacking

- **Concatenation** joins arrays along an existing axis.  
- **Stacking** adds a new axis and then joins along that axis.


In [61]:
a = np.array([[1, 2],
               [3, 4]])
b = np.array([[5, 6],
               [7, 8]])

print("a =\n", a)
print("b =\n", b)

print("\nconcatenate along axis=0 (rows):\n", np.concatenate([a, b], axis=0))
print("\nconcatenate along axis=1 (cols):\n", np.concatenate([a, b], axis=1))

a =
 [[1 2]
 [3 4]]
b =
 [[5 6]
 [7 8]]

concatenate along axis=0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate along axis=1 (cols):
 [[1 2 5 6]
 [3 4 7 8]]


In [62]:
stack0 = np.stack([a, b], axis=0)
stack1 = np.stack([a, b], axis=1)

print("stack axis=0 shape:", stack0.shape)
print("stack axis=1 shape:", stack1.shape)

stack axis=0 shape: (2, 2, 2)
stack axis=1 shape: (2, 2, 2)


## Broadcasting

Broadcasting lets NumPy apply operations to arrays of different shapes
when those shapes are compatible.


In [63]:
row = np.array([1, 2, 3])        # shape (3,)
col = np.array([[10], [20]])     # shape (2, 1)

print("row shape:", row.shape)
print("col shape:", col.shape)

result = col + row
print("\ncol + row =\n", result)
print("result shape:", result.shape)

row shape: (3,)
col shape: (2, 1)

col + row =
 [[11 12 13]
 [21 22 23]]
result shape: (2, 3)


## Elementwise vs matrix multiplication

- `*` performs elementwise multiplication.  
- `@` performs matrix multiplication (linear algebra).


In [64]:
A = np.array([[1, 2],
               [3, 4]])
B = np.array([[5, 6],
               [7, 8]])

print("A =\n", A)
print("B =\n", B)

print("\nA * B (elementwise):\n", A * B)
print("\nA @ B (matrix multiply):\n", A @ B)

A =
 [[1 2]
 [3 4]]
B =
 [[5 6]
 [7 8]]

A * B (elementwise):
 [[ 5 12]
 [21 32]]

A @ B (matrix multiply):
 [[19 22]
 [43 50]]


## Summary

In this recitation we:

- Created NumPy arrays of different dimensions
- Inspected their attributes (`ndim`, `shape`, `size`, `dtype`)
- Practised indexing, slicing, and boolean masking
- Used axis‑based operations such as sums and argmax
- Reshaped, transposed, expanded, and squeezed arrays
- Combined arrays with concatenation and stacking
- Saw how broadcasting lets us work with different shapes
- Distinguished elementwise from matrix multiplication

For more details, see the official NumPy documentation: https://numpy.org/doc/
